name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Please describe why this is necessary.
      placeholder: >
        A description of what the problem is, or what motivates the feature you are requesting
  - type: textarea
    attributes:
      label: Describe the functionality you are proposing.
      placeholder: >
        A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Additional context
      placeholder: >
        Add any other context or screenshots about the feature request here.

