# Auto assign every PR to its author when opened
name: Auto-assign PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-request: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    concurrency:
      # Only run one at a time for each user.
      group: ${{ github.actor }}-issue-assign
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
