name: Auto assign the issue via `take` comment

on:
  issue_comment:
    types: created

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: (!github.event.issue.pull_request) && github.event.comment.body == 'take'
    concurrency:
      # Only run one at a time for each user.
      group: ${{ github.actor }}-auto-assign-issue
    steps:
      - name: Check if issue can be assigned
        id: check-assignee
        # Check if the user is already assigned to the issue
        run: |
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -LI https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees/${{ github.event.comment.user.login }} -o /dev/null -w '%{http_code}' -s)
          echo "HTTP_CODE=$RESPONSE" >> $GITHUB_ENV

      - name: Assign issue to commenter
        if: env.HTTP_CODE == '204'
        # Assign the issue to the user who commented 'take'
        run: |
          echo "Assigning issue #${{ github.event.issue.number }} to @${{ github.event.comment.user.login }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log failure to assign
        if: env.HTTP_CODE != '204'
        # Log the failure to assign the issue
        run: |
          echo "Issue #${{ github.event.issue.number }} cannot be assigned to @${{ github.event.comment.user.login }}. HTTP response code: ${{ env.HTTP_CODE }}"
