name: Run tests to ensure we can compile across arrow versions

on: [workflow_dispatch, push, pull_request]

jobs:
  arrow_integration_test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    # skip running windows tests on every PR since they are slow
    if: ${{ !(github.event_name == 'pull_request' && matrix.os == 'windows-latest') }}
    steps:
      - uses: actions/checkout@v3
      - name: Install minimal stable rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: run integration tests
        shell: bash
        run: pushd integration-tests && ./test-all-arrow-versions.sh
